### ISSUE TITLE
Readme changelog command is broken

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#539]
## Bug Description

When running `npm run readme -- -m "1.5.0"` earlier to prepare the 1.5.0 release, I received an error causing the changelog to not be generated:
```
TypeError: Octokit is not a constructor
    at getChangelog (.../performance/bin/plugin/commands/changelog.js:268:18)
    at updateReadme (.../performance/bin/plugin/commands/readme.js:158:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async exports.handler (.../performance/bin/plugin/commands/readme.js:54:2)
    at async Command.<anonymous> (.../performance/bin/plugin/cli.js:18:4)
```

Please test running it on your side as well. If this is a consistent error, something broke (possibly during the recent dependency update in #511) and we need to fix it.

**Comment by pushpakpop** [comment]
I can reproduce the issue on my end with the same error.

**Comment by mukeshpanchal27** [comment]
I also replicate the issue in my end.

Gutenberg still used old version for `@octokit/rest` https://github.com/WordPress/gutenberg/blob/trunk/package.json#L98.

I will take a look and submit PR for it.
